// Autogenerated file
import { ExtendableError } from '~/classes/ExtendableError'

export class <%= spec.name %> extends ExtendableError {
  name = '<%= spec.name %>'

  config
  request
  response

  constructor (message: string = '', payload: any = {}) {
    super(message, payload)
    Object.setPrototypeOf(this, <%= spec.name %>.prototype)

    this.config = payload.config
    this.request = payload.request
    this.response = payload.response
  }
}
