// Autogenerated file
import { ExtendableError } from '~/classes/ExtendableError'

export class <%= spec.name %> extends ExtendableError {
  name = '<%= spec.name %>'

  code
  config
  request
  response

  constructor (message: string = '', payload: any = {}, code: number = 0) {
    super(message, payload)
    Object.setPrototypeOf(this, <%= spec.name %>.prototype)

    this.code = code
    this.config = payload.config
    this.request = payload.request
    this.response = payload.response
  }

  is (code): boolean {
    return this.code === code
  }
}
