// Autogenerated file

import { IHttpPromise, IHttpRequestConfig } from '~/services/http'

import { Product } from './definitions/Product'

import { OrderItems } from './definitions/OrderItems'

import { OrderItem } from './definitions/OrderItem'

import { IOrderParams } from './params/IOrderParams'

import { IGetProductsListResponse } from './responses/IGetProductsListResponse'

export interface IApiService {

    getProductsList(params?: void | null, config?: IHttpRequestConfig): IHttpPromise<IGetProductsListResponse>

    order(params: IOrderParams, config?: IHttpRequestConfig): IHttpPromise<void>

}
