// Autogenerated file
import { ExtendableError } from '~/classes/ExtendableError'

export class ApiServiceRequireError extends ExtendableError {
    name = 'ApiServiceRequireError'

    config
    request
    response

    constructor(message: string = '', payload: any = {}) {
        super(message, payload)
        Object.setPrototypeOf(this, ApiServiceRequireError.prototype)

        this.config = payload.config
        this.request = payload.request
        this.response = payload.response
    }
}
