export const ApiServiceErrorsCodes = {
    UNDEFINED_CLIENT_ERROR: 'UNDEFINED_CLIENT_ERROR'

    , INCORRECT_INPUT_DATA: 'INCORRECT_INPUT_DATA'

    , SOME_PRODUCTS_NOT_FOUND: 'SOME_PRODUCTS_NOT_FOUND'

}
